### ISSUE TITLE
Item spawned behind "leave map wall"

### ISSUE THREAD

**Issue by BottledByte** [Tomash667/carpg#418] opened 2020-03-27 12:40 UTC
I noticed that a pickable item (healing herb) spawned behind "leave map wall" while I was at Academy.
Nothing critical, but it may cause player confusion and create unobtainable items.
I do not know if other areas and items are affected.
![_screenshot](https://user-images.githubusercontent.com/62666666/77756348-46b0ff00-702f-11ea-881a-d3ced51e04ce.png)

**Comment by Tomash667** [comment] 2020-03-27 12:45
It was intended but if it's confusing I can easily fix it.

**Comment by BottledByte** [comment] 2020-03-27 12:55
If it is a design decision, I do not think that it should be changed. Confusion is not a problem, but if this can happen to some quest item and it would make it unobtainable, it could result in "undoable" quest. I do not know if quest items are subject to this behaviour, but if they are, I would say that this is a bug.

**Comment by Tomash667** [comment] 2020-03-27 14:37
It is only used for randomly spawned herbs.

**Comment by Tomash667** [comment] 2020-03-27 21:02
Fixed in 0.14.

**Closed** 2020-03-27 21:02 UTC
Labels: bug
